### ISSUE TITLE
build fails under ubuntu 14.04 64 bit

### ISSUE THREAD

**Issue by johanovic** [csgo-data/demoinfogo-linux#19]
demoinfogo-linux/protobuf-2.5.0/src/.libs/lt-protoc: error while loading shared libraries: libprotoc.so.8: cannot open shared object file: No such file or directory
make[3]: *** [unittest_proto_middleman] Error 127

**Comment by johanovic** [comment]
Can I provide any extra info to get this fixed?

**Comment by kaimallea** [comment]
Hey @johanovic, I'm able to get this working fine. How did you compile protobuf? Did you use the commands provided in the `Makefile` located in the root of the repo? 

Try deleting the protobuf-2.5.0 folder, and re-running the commands to download, and compile it, from the root of the repo:

```bash
rm -rf protobuf-2.5.0
make get_protobuf
make protobuf
```

Once that complete, run `make` to compile demoinfogo.

**Comment by kaimallea** [comment]
@johanovic did that work for you?

**Comment by kaimallea** [comment]
I'll close this for now; let me know if you're still having issues and I'll re-open it.
