### ISSUE TITLE
Segmentation fault after player disconnect (OS X)

### ISSUE THREAD

**Issue by cltatman** [csgo-data/demoinfogo-linux#20]
processing [this GOTV demo](https://drive.google.com/file/d/0B8GxtqSAkc3qcmlyTl9DajVfbHc/view?usp=sharing) i get a segfault after receiving `Player Toby (id:21) disconnected. reason:Kicked by Console`

no problems playing the demo in-game, any ideas?

**Comment by taylorfinnell** [comment]
Seeing it too both in this repo and building the code in the latest demoinfogo.zip from the SDK. I have traced it here https://github.com/csgo-data/demoinfogo-linux/blob/master/src/demofiledump.cpp#L1519. If you comment that out the demo is parsed fully without crashing. However, I have no idea why that has to be commented out. Anyone have any ideas?

**Comment by kaimallea** [comment]
@taylorfinnell hey there. I haven't had a chance to dive into this on OSX, but great job isolating it to that line. I wonder if the `clear()` call needs to reside inside the `if ( g_bDumpStringTables )` block? Weird that only the `printf()` call would be in there to advertise a clear, but the actual `clear()` gets called no matter what. Just a guess.

BTW I accept pull requests :smile:

**Comment by taylorfinnell** [comment]
Hey! I think that's just a guard that verbosity of the output. It happens when the player disconnect is called and the FindPlayerInfo fails. I assume the lookup fails because the clear function call removed the entity it needed. I wonder if something is somehow ending up out of order or something

**Comment by kaimallea** [comment]
You are correct. I see that `pPlayerInfo` is NULL after the lookup fails, however, the code attempts to modify it anyway. The simple fix would be to perform a check first:

```diff
diff --git a/src/demofiledump.cpp b/src/demofiledump.cpp
index 006bd36..b13892d 100644
--- a/src/demofiledump.cpp
+++ b/src/demofiledump.cpp
@@ -310,9 +310,11 @@ bool HandlePlayerConnectDisconnectEvents( const CSVCMsg_GameEvent &msg, const CS
 			}
 			// mark the player info slot as disconnected
 			player_info_t *pPlayerInfo = FindPlayerInfo( userid );
-			strcpy( pPlayerInfo->name, "disconnected" );
-			pPlayerInfo->userID = -1;
-			pPlayerInfo->guid[ 0 ] = 0;
+			if (pPlayerInfo) {
+				strcpy( pPlayerInfo->name, "disconnected" );
+				pPlayerInfo->userID = -1;
+				pPlayerInfo->guid[ 0 ] = 0;
+			}
 		}
 		else
 		{
```

Want to send a pull request? :smiley:

**Comment by kaimallea** [comment]
I'll just do it since I'm in the process of creating another PR for a separate bug. tyvm for your detective work! @taylorfinnell

**Comment by taylorfinnell** [comment]
I wish we knew if adding the NULL check is the proper fix, or if the PlayerInfo list is being cleared at the wrong time or in an improper way. Either way, at least this prevents the crash and the parser still acts reasonably.

**Comment by kaimallea** [comment]
Yea I couldn't tell; it was a bot kicked by console that never went through the connect step before it was disconnected (there were 11 items in the vector and it wasn't one of them).
