### ISSUE TITLE
Exit code 1 for several replays that seem to work.

### ISSUE THREAD

**Issue by mehdi-kaytoue** [csgo-data/demoinfogo-linux#21]
Thanks for this nice parser!

I got around 1500 replays from gosugamers and I am checking if they are parsable.
For that I just do a ./demoingogo $filename || echo "problem"
I have an exit code of 1 for a lot a replays, but when I look the output, it seems that the parsing is done correctly, See e.g. "2779_R1_logiX eSp_TCM-Gamin.dem" on gosugamers.

Any idea? Is this a problem?

Btw, I d like to know if this projet is still maintained, as I might use it quite a lot. 

Thanks a lot!!
Cheers

**Comment by kaimallea** [comment]
Hi! Thanks for reporting this. I _try_ to keep this up-to-date with changes that Valve makes to demoinfogo, so there aren't a lot of updates. Having said that, I will attempt to fix bugs if I can. I'll take a look at this.

**Comment by taylorfinnell** [comment]
It could perhaps be #20. I can't find the demo file you referenced, can you link it?

**Comment by mehdi-kaytoue** [comment]
Hey! Thanks guys.
Thats was an example of replay for which I had a 1 exit code:
http://www.gosugamers.net/demos/5783-logix-esports-cs-vs-tcm-gaming/download

Btw i realized it's worth mentioning I am using macosx

Cheers

**Comment by kaimallea** [comment]
Apparently `1` is always returned by `main()`: https://github.com/csgo-data/demoinfogo-linux/blob/master/src/demoinfogo.cpp#L135

I wonder if that's a Windows thing? It's in Valve's original source, too. Fixing now.

**Comment by taylorfinnell** [comment]
This bug is not fixed. If you run his demo through with the `-deathcsv` flag you get nonsense output. The issue is that `player_info_t` is a different size struct in older versions of these demos. The code needs to take the `version` of the `player_info_t` into account before parsing that data.

**Comment by kaimallea** [comment]
@taylorfinnell sounds like a new, separate bug to me. :smiley:

**Comment by taylorfinnell** [comment]
Yep, I will open and issue a bit later tonight with the updated info

**Comment by kaimallea** [comment]
Excellent, thanks again. :-)
