### ISSUE TITLE
make get_protobuf won't work

### ISSUE THREAD

**Issue by WillBrindle** [csgo-data/demoinfogo-linux#28]
This command will no longer work since protobuf moved to github from googlecode. You need to update the url to
https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz

 and include the -L command to follow redirects. Possibly -k as well as I know I've had to use this before when downloading from github. I didn't try without as I was just trying to get this up and running as quick as possible.

**Comment by kaimallea** [comment]
Thank you for reporting this! I've updated the Makefile to use the new URL. 😃
